-- =====================================================================
-- V1 : schéma d'origine de l'application (celui que Hibernate créait
-- automatiquement avant l'arrivée de Flyway).
-- "IF NOT EXISTS" permet d'appliquer ce script sans erreur sur une base
-- déjà créée par l'ancienne version : les tables existantes sont gardées.
-- =====================================================================

CREATE TABLE IF NOT EXISTS agents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    identifiant   VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS delegues (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom             VARCHAR(255) NOT NULL,
    filiere_niveau  VARCHAR(255) NOT NULL,
    identifiant     VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS materiel (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation     VARCHAR(255) NOT NULL,
    categorie_id    BIGINT NOT NULL REFERENCES categories (id),
    type_gestion    VARCHAR(255) NOT NULL,
    code_unique     VARCHAR(255) UNIQUE,
    statut          VARCHAR(255) NOT NULL,
    quantite_stock  INTEGER
);

CREATE TABLE IF NOT EXISTS emprunts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegue_id           BIGINT NOT NULL REFERENCES delegues (id),
    salle                VARCHAR(255) NOT NULL,
    statut_emprunt       VARCHAR(255) NOT NULL,
    agent_sortie_id      BIGINT REFERENCES agents (id),
    date_sortie          TIMESTAMP(6) NOT NULL,
    heure_retour_prevue  TIME(6),
    agent_retour_id      BIGINT REFERENCES agents (id),
    date_retour          TIMESTAMP(6),
    observations         TEXT
);

CREATE TABLE IF NOT EXISTS details_emprunt (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emprunt_id   BIGINT NOT NULL REFERENCES emprunts (id),
    materiel_id  BIGINT NOT NULL REFERENCES materiel (id),
    quantite     INTEGER NOT NULL,
    etat_retour  VARCHAR(255)
);
