-- =====================================================================
-- V2 : comptes (actif / administrateur), salles, seuil de stock,
-- historique complet des emprunts (refus, annulation, retour).
-- =====================================================================

-- ---------- Contraintes CHECK générées par l'ancienne version ----------
-- Hibernate créait des contraintes figées sur les valeurs des enums :
-- on les remplace par les nôtres, qui acceptent les nouveaux statuts.
ALTER TABLE emprunts        DROP CONSTRAINT IF EXISTS emprunts_statut_emprunt_check;
ALTER TABLE details_emprunt DROP CONSTRAINT IF EXISTS details_emprunt_etat_retour_check;
ALTER TABLE materiel        DROP CONSTRAINT IF EXISTS materiel_statut_check;
ALTER TABLE materiel        DROP CONSTRAINT IF EXISTS materiel_type_gestion_check;

-- ---------- Agents ----------
ALTER TABLE agents ADD COLUMN IF NOT EXISTS administrateur BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS actif          BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE agents SET administrateur = TRUE WHERE LOWER(role) LIKE 'admin%';

-- ---------- Délégués ----------
ALTER TABLE delegues ADD COLUMN IF NOT EXISTS actif         BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE delegues ADD COLUMN IF NOT EXISTS date_creation TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ---------- Matériel ----------
UPDATE materiel SET quantite_stock = 1 WHERE quantite_stock IS NULL;
ALTER TABLE materiel ALTER COLUMN quantite_stock SET NOT NULL;
ALTER TABLE materiel ADD COLUMN IF NOT EXISTS seuil_alerte INTEGER NOT NULL DEFAULT 5;

ALTER TABLE materiel ADD CONSTRAINT ck_materiel_type_gestion
    CHECK (type_gestion IN ('DURABLE', 'CONSOMMABLE'));
ALTER TABLE materiel ADD CONSTRAINT ck_materiel_statut
    CHECK (statut IN ('DISPONIBLE', 'EMPRUNTE', 'A_VERIFIER', 'MAINTENANCE', 'HS'));
ALTER TABLE materiel ADD CONSTRAINT ck_materiel_quantites
    CHECK (quantite_stock >= 0 AND seuil_alerte >= 0);

-- ---------- Emprunts ----------
-- date_sortie désignait jusqu'ici la date de la demande : elle devient
-- "date_demande", et date_sortie ne sera remplie qu'à la remise du matériel.
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS date_demande TIMESTAMP(6);
UPDATE emprunts SET date_demande = date_sortie WHERE date_demande IS NULL;
ALTER TABLE emprunts ALTER COLUMN date_demande SET NOT NULL;
ALTER TABLE emprunts ALTER COLUMN date_sortie DROP NOT NULL;
UPDATE emprunts SET date_sortie = NULL WHERE statut_emprunt = 'EN_ATTENTE';

-- Un emprunt rendu passe au statut RETOURNE (avant : EN_COURS + date de retour)
UPDATE emprunts SET statut_emprunt = 'RETOURNE'
    WHERE statut_emprunt = 'EN_COURS' AND date_retour IS NOT NULL;

ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS agent_refus_id  BIGINT REFERENCES agents (id);
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS motif_refus     TEXT;
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS date_traitement TIMESTAMP(6);

ALTER TABLE emprunts ADD CONSTRAINT ck_emprunts_statut
    CHECK (statut_emprunt IN ('EN_ATTENTE', 'EN_COURS', 'RETOURNE', 'REFUSEE', 'ANNULEE'));

-- ---------- Détails d'emprunt ----------
ALTER TABLE details_emprunt ADD CONSTRAINT ck_details_etat_retour
    CHECK (etat_retour IS NULL OR etat_retour IN ('BON_ETAT', 'A_VERIFIER', 'ENDOMMAGE', 'VIDE_EPUISE'));
ALTER TABLE details_emprunt ADD CONSTRAINT ck_details_quantite
    CHECK (quantite > 0);

-- ---------- Salles ----------
CREATE TABLE IF NOT EXISTS salles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO salles (nom) VALUES ('101'), ('102'), ('Amphi A'), ('Labo Info')
    ON CONFLICT (nom) DO NOTHING;

-- Les salles déjà utilisées dans d'anciens emprunts sont reprises dans la liste
INSERT INTO salles (nom)
    SELECT DISTINCT salle FROM emprunts
    ON CONFLICT (nom) DO NOTHING;

-- ---------- Index pour les listes et statistiques ----------
CREATE INDEX IF NOT EXISTS idx_emprunts_statut   ON emprunts (statut_emprunt);
CREATE INDEX IF NOT EXISTS idx_emprunts_delegue  ON emprunts (delegue_id);
CREATE INDEX IF NOT EXISTS idx_emprunts_demande  ON emprunts (date_demande);
CREATE INDEX IF NOT EXISTS idx_details_emprunt   ON details_emprunt (emprunt_id);
CREATE INDEX IF NOT EXISTS idx_details_materiel  ON details_emprunt (materiel_id);
CREATE INDEX IF NOT EXISTS idx_materiel_categorie ON materiel (categorie_id);
