-- =====================================================================
-- V3 : retour article par article (scan QR), transferts entre délégués,
-- réservations à l'avance, notifications.
-- =====================================================================

-- ---------- Emprunts : mode, réservation, rappel de retard, origine ----------
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS mode VARCHAR(255) NOT NULL DEFAULT 'DEMANDE';
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS date_reservation DATE;
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS heure_debut TIME(6);
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS rappel_retard_envoye BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE emprunts ADD COLUMN IF NOT EXISTS emprunt_origine_id BIGINT REFERENCES emprunts (id);

ALTER TABLE emprunts DROP CONSTRAINT IF EXISTS ck_emprunts_statut;
ALTER TABLE emprunts ADD CONSTRAINT ck_emprunts_statut
    CHECK (statut_emprunt IN ('RESERVEE', 'EN_ATTENTE', 'EN_COURS', 'RETOURNE', 'REFUSEE', 'ANNULEE'));
ALTER TABLE emprunts ADD CONSTRAINT ck_emprunts_mode
    CHECK (mode IN ('DEMANDE', 'SCAN', 'TRANSFERT', 'RESERVATION', 'AGENT'));

CREATE INDEX IF NOT EXISTS idx_emprunts_date_reservation ON emprunts (date_reservation);

-- ---------- Détails : retour par article ----------
ALTER TABLE details_emprunt ADD COLUMN IF NOT EXISTS date_retour TIMESTAMP(6);
ALTER TABLE details_emprunt ADD COLUMN IF NOT EXISTS mode_retour VARCHAR(255);
ALTER TABLE details_emprunt ADD COLUMN IF NOT EXISTS remarque_retour TEXT;

ALTER TABLE details_emprunt ADD CONSTRAINT ck_details_mode_retour
    CHECK (mode_retour IS NULL OR mode_retour IN ('DEMANDE', 'SCAN', 'TRANSFERT', 'RESERVATION', 'AGENT'));

-- Les fiches déjà rendues avant cette version : chaque article est rendu au poste, à la date de la fiche
UPDATE details_emprunt d
   SET date_retour = e.date_retour, mode_retour = 'AGENT'
  FROM emprunts e
 WHERE d.emprunt_id = e.id AND e.statut_emprunt = 'RETOURNE' AND d.date_retour IS NULL;

-- ---------- Transferts ----------
CREATE TABLE IF NOT EXISTS transferts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materiel_id          BIGINT NOT NULL REFERENCES materiel (id),
    detail_source_id     BIGINT NOT NULL REFERENCES details_emprunt (id),
    demandeur_id         BIGINT NOT NULL REFERENCES delegues (id),
    detenteur_id         BIGINT NOT NULL REFERENCES delegues (id),
    statut               VARCHAR(255) NOT NULL CHECK (statut IN ('EN_ATTENTE', 'ACCEPTE', 'REFUSE', 'ANNULE')),
    salle                VARCHAR(255) NOT NULL,
    heure_retour_prevue  TIME(6),
    date_demande         TIMESTAMP(6) NOT NULL,
    date_reponse         TIMESTAMP(6),
    emprunt_cree_id      BIGINT REFERENCES emprunts (id)
);
CREATE INDEX IF NOT EXISTS idx_transferts_detenteur ON transferts (detenteur_id, statut);
CREATE INDEX IF NOT EXISTS idx_transferts_demandeur ON transferts (demandeur_id, statut);

-- ---------- Notifications ----------
CREATE TABLE IF NOT EXISTS notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinataire_type  VARCHAR(255) NOT NULL CHECK (destinataire_type IN ('AGENT', 'DELEGUE')),
    destinataire_id    BIGINT NOT NULL,
    categorie          VARCHAR(255) NOT NULL
        CHECK (categorie IN ('DEMANDE', 'VALIDATION', 'REFUS', 'TRANSFERT', 'RETOUR', 'RETARD', 'RESERVATION', 'INFO')),
    titre              VARCHAR(255) NOT NULL,
    message            TEXT NOT NULL,
    lien               VARCHAR(255),
    lue                BOOLEAN NOT NULL DEFAULT FALSE,
    date_creation      TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_destinataire ON notifications (destinataire_type, destinataire_id, lue);
